# Generated by Django 5.0.7 on 2024-08-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image_title',
            field=models.CharField(default='product', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
