# Generated by Django 5.0.7 on 2024-08-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_image_title_alter_auction_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='image_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='product',
        ),
    ]
