# Generated by Django 5.0.7 on 2024-08-07 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_image_title_auction_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
